[package]
name = "fsdd"
edition = "2024"
publish = false

[[example]]
name = "fsdd"

[dependencies]
async-channel      = { version = "2.5.0" }
app                = { path = "../../crates/app" }
burn               = { version = "0.20.0", features = ["autodiff", "dataset"] }
clap               = { version = "4.5.54", features = ["derive"] }
mel_spec           = { version = "0.3.4" }
ndarray            = { version = "0.16.1" }
plotters           = { version = "0.3.7" }
rustfft            = { version = "6.4.1" }
tokio              = { version = "1.49.0", features = ["fs"] }
tracing            = { version = "0.1" }
tracing-appender   = { version = "0.2" }
tracing-subscriber = { version = "0.3" }
wavers             = { version = "1.5.1" }